name    'guyguy333-owncloud'
version '0.1.0'
source 'https://github.com/guyguy333/puppet-owncloud'
author 'Guillaume Delbergue'
summary 'Puppet module to set up an instance of ownCloud'
description 'Installs owncloud and required mysql db/user.'
project_page 'https://github.com/guyguy333/puppet-owncloud'
dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/mysql', '>= 2.1.0'
dependency 'puppetlabs/stdlib', '>= 2.3.1'